import { Geist, Geist_Mono } from "next/font/google";
import { DM_Sans } from "next/font/google";
import { Caveat_Brush } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";


const caveatBrush=Caveat_Brush({
  variable: "--font-caveat-brush",
  weight:'400',
  subsets:["latin"]

})

const dmSans=DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"]
})
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.variable} ${caveatBrush.variable} font-sans antialiased text-text-primary dark:text-text-secondary w-full`}
      >
        {children}
        <Toaster/>
      </body>
    </html>
  );
}
